- name: Deploy Application
  hosts: all #which hosts in inventory to run this against
  gather_facts: yes #gather useful variables about the remote hosts 
  tasks:
    - name: Download Release Zip File
      become: yes #sudo 
      get_url: 
        url: https://github.com/servian/TechTestApp/releases/download/v.0.6.0/TechTestApp_v.0.6.0_linux64.zip
        dest: .
    - name: Unzip Release Zip File
      become: yes
      unarchive:
        src: TechTestApp_v.0.6.0_linux64.zip
        dest: .
        #influence whether src to be transferred or is present remotely
        remote_src: yes #go to remote/target machine for the src folder
    - name: Configure Application with Correct Database Details
      become: yes
      vars: #template variables to host variables in inventory.yml 
        db_username: "{{ db_username_i }}"
        db_password: "{{ db_password_i }}"
        db_name: "{{ db_name_i }}"
        db_port: "{{ db_port_i }}"
        db_host: "{{ db_host_i }}"
      template:
        dest: dist/conf.toml
        src: templates/conf.toml.tpl
    - name: Create Tables in Database and Seed it with Test Data
      become: yes
      shell: 
        cmd: ./TechTestApp updatedb -s #-s skips creating database itself
      args:
        chdir: dist
    - name: Move Release Files for Correct ListenPort & ListenHost
      become: yes
      shell: #move files to the root for Service File
        cmd: mv dist /etc/app/
    - name: Copy SystemD Service File to server
      become: yes
      copy:
        src: servian.service
        dest: /etc/systemd/system/servian.service
        owner: root
    - name: Start Service
      become: yes
      systemd:
        name: servian
        state: started
        enabled: yes #service starts on boot
        daemon_reload: yes #make sure systemd has read any changes



