- name: Deploy Application
  hosts: all #which hosts in inventory to run this against
  gather_facts: yes #gather useful variables about the remote hosts 
  tasks:
    - name: Ensure App Directory Exists
      become: yes
      file:
        path: /etc/app
        state: directory
    - name: Download & Unzip Release Zip File
      become: yes
      unarchive:
        src: https://github.com/servian/TechChallengeApp/releases/download/v.0.7.0/TechChallengeApp_v.0.7.0_linux64.zip
        dest: /etc/app/ #place release files in root for Service File
        #influence whether src to be transferred or is present remotely
        remote_src: yes #go to remote/target machine for the src folder
    - name: Configure Application With Correct Database Details
      become: yes
      vars: #template variables to host variables in inventory.yml 
        db_username: "{{ db_username_i }}"
        db_password: "{{ db_password_i }}"
        db_name: "{{ db_name_i }}"
        db_port: "{{ db_port_i }}"
        db_host: "{{ db_host_i }}"
      template:
        src: templates/conf.toml.tpl
        dest: /etc/app/dist/conf.toml
    - name: Copy App Service Configuration To Server
      become: yes
      copy:
        src: servian.service
        dest: /etc/systemd/system/
    - name: Start Service
      become: yes
      systemd:
        name: servian.service
        state: started #ensure service is started
        #Auto restart in event of a server reboot
        enabled: yes #service starts on boot
        daemon_reload: yes #make sure systemd has read any changes
    - name: Create Tables In Database And Seed it With Test Data
      become: yes
      shell: 
        cmd: ./TechChallengeApp updatedb -s #-s skips creating database itself
        chdir: /etc/app/dist/



